// USER ROLES
const ROLES = {
  USER: "USER",
  RESTAURANT: "RESTAURANT",
  DELIVERY: "DELIVERY",
  ADMIN: "ADMIN"
};

// ORDER STATUS FLOW (Zomato-style)
const ORDER_STATUS = {
  CREATED: "CREATED",
  PAID: "PAID",
  ACCEPTED: "ACCEPTED",
  PREPARING: "PREPARING",
  PICKED: "PICKED",
  DELIVERED: "DELIVERED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED"
};

module.exports = {
  ROLES,
  ORDER_STATUS
};
